"use strict";
let a = 1;
let b = 2;
let c;
c = a + b;
console.log("Tổng: ", c);
c = a - b;
console.log("Hiệu: ", c);
c = a * b;
console.log("Tích: ", c);
c = a / b;
console.log("Thương: ", c);
let num1 = "1";
let num2 = true;
let num3;
num3 = +num1 + +num2;
console.log("Tổng: ", num3);
num3 = +num1 - +num2;
console.log("Hiệu: ", num3);
num3 = +num1 * +num2;
console.log("Tích: ", num3);
num3 = +num1 / +num2;
console.log("Thương: ", num3);
